version: '3'

services:
  httpfrontendgsmmods:
    image: node:11.10-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    command: >
      /bin/sh -c "npm install &&
        npm run start"